name: check & test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: moonbitlang/setup-moonbit@v1
        with:
          moonbit-version: 0.10.3

      - name: moon check
        run: |
          moon check

      - name: moon test
        run: |
          moon test

      - name: moon fmt --deny-warn
        run: |
          moon fmt --deny-warn

      - name: moon info --deny-warn
        run: |
          moon info --deny-warn
